apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-replicaset
  labels:
    tier: frontend
    app: nginx
specs:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template: 
    metadata: 
      name: nginx-2
      labels:
        app: myapp
    specs:
      container: nginx
      image: nginx
